version: "3"

services:
  # flask:
  #   container_name: carl_frontend
  #   environment:
  #     - POSTGRES_HOST=${POSTGRES_HOST}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   build: ./build
  #   ports:
  #     - 127.0.0.1:8080:8080
  #   security_opt:
  #     - no-new-privileges:true
  #   # networks:
  #   #   - net
  #   restart: unless-stopped
  #   depends_on:
  #     - db

  db:
    image: postgres
    container_name: carl_backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
     - 127.0.0.1:5432:5432
    # expose:
    #   - 5432
    security_opt:
      - no-new-privileges:true
    # networks:
    #   - net
    volumes:
      - ./data:/var/lib/postgresql/data

# networks:
#   net:
  

