name: deploy
run-name: ${{ github.actor }} - deploy carl
on:
  push:
    tags: [ 'v[0-9]+.[0-9]+' ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compose down
        run: cd /deploy && docker-compose down
      - name: stage
        run: |
          cd /deploy &&
          rm -rf * && 
          cp -R /home/runner/_work/Team4/Team4/carl/build /deploy/ &&
          cp /deploy/.save/docker-compose.yml /deploy/docker-compose.yml
      - name: compose-up
        run: |
          cd /deploy &&
          docker stop carl_frontend carl_backend &&
          docker rm carl_frontend carl_backend &&
          docker-compose up -d --remove-orphans
      - run: echo "Status:${{ job.status }}."

