name: deploy
run-name: ${{ github.actor }} - deploy carl
on:
  push:
    tags: [ 'v[0-9]+.[0-9]+' ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compose down
        run: |
          cd /deploy
          docker-compose down
          docker ps -q --filter "name=carl_backend" | grep -q . && docker stop carl_backend && docker rm -fv carl_backend || true
          docker ps -q --filter "name=carl_frontend" | grep -q . && docker stop carl_frontend && docker rm -fv carl_frontend || true
      - name: stage
        run: |
          cd /deploy
          rm -rf *
          cp -R /home/runner/_work/Team4/Team4/carl/build /deploy/
          cp /deploy/.save/docker-compose.yml /deploy/docker-compose.yml
      - name: compose-up
        run: |
          cd /deploy
          docker-compose up -d --remove-orphans
      - run: echo "Status:${{ job.status }}."

